/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_fruit_androiddemo_MainActivityKt */

#ifndef _Included_dev_fruit_androiddemo_MainActivityKt
#define _Included_dev_fruit_androiddemo_MainActivityKt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_fruit_androiddemo_MainActivityKt
 * Method:    rustLayout
 * Signature: (Ldev/fruit/androiddemo/PlatformNode;ZII)V
 */
JNIEXPORT void JNICALL Java_dev_fruit_androiddemo_MainActivityKt_rustLayout
  (JNIEnv *, jclass, jobject, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
